/**
 * SRD spell library — types, lazy loader, search, and mapping to the app's Spell model.
 *
 * Data credit: Open5e (https://open5e.com) · CC-BY-4.0 / OGL
 * Sources: SRD 5.1 (2014) and SRD 5.2 (2024) by Wizards of the Coast.
 *
 * srd-spells.json   — generated by `npm run gen:spells` (EN data, do not hand-edit)
 * srd-spells-pt.json — PT-BR translation overlay, keyed by slug (hand-edited / committed)
 *
 * The app does NOT fetch at runtime — this is fully offline-capable.
 */

import type { Spell, SpellSchool } from '@/domain/character'
import type { Lang } from '@/i18n/types'

// ─── Public attribution constant ────────────────────────────────────────────

export const SRD_ATTRIBUTION =
  'Dados do SRD via Open5e (CC-BY-4.0 / OGL).'

// ─── Types ───────────────────────────────────────────────────────────────────

export interface SrdSpellPt {
  name: string
  castingTime: string
  range: string
  duration: string
  components: string
  material: string
  description: string
  higherLevel: string
}

export interface SrdSpell {
  slug: string
  name: string
  level: number          // 0..9
  school: string         // lowercase: 'evocation' etc.
  castingTime: string    // "1 action"
  range: string          // "150 feet"
  components: string     // "V, S, M"
  material: string       // "a tiny ball of bat guano and sulfur"
  duration: string
  concentration: boolean
  ritual: boolean
  description: string
  higherLevel: string    // empty string when absent
  classes: string[]      // ["Sorcerer", "Wizard"]
  edition: '2014' | '2024'
  pt?: SrdSpellPt
}

interface SrdSpellsJson {
  _meta: {
    attribution: string
    generated: string
    v1Count: number
    v2Count: number
    totalCount: number
  }
  spells: SrdSpell[]
}

// ─── Lazy loader ─────────────────────────────────────────────────────────────

let cache: SrdSpell[] | null = null

export async function loadSrdSpells(): Promise<SrdSpell[]> {
  if (!cache) {
    const [enMod, ptMod] = await Promise.all([
      import('./srd-spells.json'),
      import('./srd-spells-pt.json'),
    ])
    const ptMap = (ptMod.default ?? ptMod) as Record<string, SrdSpellPt>
    cache = (enMod.default as SrdSpellsJson).spells.map(s => {
      const p = ptMap[s.slug]
      return p ? { ...s, pt: p } : s
    })
  }
  return cache
}

// ─── Search ──────────────────────────────────────────────────────────────────

const MAX_RESULTS = 50

export function searchSpells(
  all: SrdSpell[],
  query: string,
  opts?: { level?: number; school?: string },
): SrdSpell[] {
  const q = query.trim().toLowerCase()
  const level = opts?.level
  const school = opts?.school?.trim().toLowerCase()

  let filtered = all
  if (level !== undefined) filtered = filtered.filter(s => s.level === level)
  if (school !== undefined && school !== '') {
    filtered = filtered.filter(s => s.school === school)
  }

  if (q === '') return filtered

  const prefix: SrdSpell[] = []
  const substring: SrdSpell[] = []

  for (const s of filtered) {
    const enName = s.name.toLowerCase()
    const ptName = (s.pt?.name ?? '').toLowerCase()
    const isPrefix = enName.startsWith(q) || (ptName !== '' && ptName.startsWith(q))
    const isSubstring = enName.includes(q) || ptName.includes(q)
    if (isPrefix) {
      prefix.push(s)
    } else if (isSubstring) {
      substring.push(s)
    }
    if (prefix.length + substring.length >= MAX_RESULTS * 2) break
  }

  return [...prefix, ...substring].slice(0, MAX_RESULTS)
}

// ─── Mapping to app model ─────────────────────────────────────────────────────

const SCHOOLS: SpellSchool[] = [
  'abjuration',
  'conjuration',
  'divination',
  'enchantment',
  'evocation',
  'illusion',
  'necromancy',
  'transmutation',
]

export function srdSchoolToApp(s: string): SpellSchool {
  const k = s.trim().toLowerCase() as SpellSchool
  return SCHOOLS.includes(k) ? k : 'abjuration'
}

const LABELS: Record<Lang, { components: string; duration: string; concentration: string; ritual: string; higher: string }> = {
  en: { components: 'Components', duration: 'Duration', concentration: 'Concentration', ritual: 'Ritual', higher: 'At higher levels' },
  pt: { components: 'Componentes', duration: 'Duração', concentration: 'Concentração', ritual: 'Ritual', higher: 'Em níveis superiores' },
}

/**
 * Composes the description the app uses with metadata that has no dedicated field
 * (components, duration, concentration, ritual, higher-level text).
 *
 * When lang='pt' and s.pt exists, uses PT text and PT labels.
 * Otherwise uses EN text and EN labels.
 */
export function srdSpellToAppFields(s: SrdSpell, lang: Lang = 'en'): Omit<Spell, 'id' | 'prepared' | 'pt'> {
  const L = LABELS[lang]
  const src = (lang === 'pt' && s.pt)
    ? { ...s.pt }
    : { name: s.name, castingTime: s.castingTime, range: s.range, duration: s.duration, components: s.components, material: s.material, description: s.description, higherLevel: s.higherLevel }

  const meta: string[] = []
  if (src.components) {
    meta.push(`${L.components}: ${src.components}${src.material ? ` (${src.material})` : ''}`)
  }
  if (src.duration) {
    meta.push(`${L.duration}: ${src.duration}${s.concentration ? ` (${L.concentration})` : ''}`)
  }
  if (s.ritual) meta.push(L.ritual)

  const parts = [src.description.trim()]
  if (src.higherLevel) parts.push(`${L.higher}: ${src.higherLevel.trim()}`)
  if (meta.length) parts.push(meta.join(' · '))

  return {
    name: src.name,
    level: s.level,
    school: srdSchoolToApp(s.school),
    castingTime: src.castingTime,
    range: src.range,
    description: parts.filter(Boolean).join('\n\n'),
  }
}
