/**
 * SRD spell library — types, lazy loader, search, and mapping to the app's Spell model.
 *
 * Data credit: Open5e (https://open5e.com) · CC-BY-4.0 / OGL
 * Sources: SRD 5.1 (2014) and SRD 5.2 (2024) by Wizards of the Coast.
 *
 * The JSON is generated by `npm run gen:spells` and committed.
 * The app does NOT fetch at runtime — this is fully offline-capable.
 */

import type { Spell, SpellSchool } from '@/domain/character'

// ─── Public attribution constant ────────────────────────────────────────────

export const SRD_ATTRIBUTION =
  'Dados do SRD via Open5e (CC-BY-4.0 / OGL).'

// ─── Types ───────────────────────────────────────────────────────────────────

export interface SrdSpell {
  slug: string
  name: string
  level: number          // 0..9
  school: string         // lowercase: 'evocation' etc.
  castingTime: string    // "1 action"
  range: string          // "150 feet"
  components: string     // "V, S, M"
  material: string       // "a tiny ball of bat guano and sulfur"
  duration: string
  concentration: boolean
  ritual: boolean
  description: string
  higherLevel: string    // empty string when absent
  classes: string[]      // ["Sorcerer", "Wizard"]
  edition: '2014' | '2024'
}

interface SrdSpellsJson {
  _meta: {
    attribution: string
    generated: string
    v1Count: number
    v2Count: number
    totalCount: number
  }
  spells: SrdSpell[]
}

// ─── Lazy loader ─────────────────────────────────────────────────────────────

let cache: SrdSpell[] | null = null

export async function loadSrdSpells(): Promise<SrdSpell[]> {
  if (!cache) {
    const mod = await import('./srd-spells.json')
    cache = (mod.default as SrdSpellsJson).spells
  }
  return cache
}

// ─── Search ──────────────────────────────────────────────────────────────────

const MAX_RESULTS = 50

export function searchSpells(
  all: SrdSpell[],
  query: string,
  opts?: { level?: number; school?: string },
): SrdSpell[] {
  const q = query.trim().toLowerCase()
  const level = opts?.level
  const school = opts?.school?.trim().toLowerCase()

  let filtered = all
  if (level !== undefined) filtered = filtered.filter(s => s.level === level)
  if (school !== undefined && school !== '') {
    filtered = filtered.filter(s => s.school === school)
  }

  if (q === '') return filtered

  const prefix: SrdSpell[] = []
  const substring: SrdSpell[] = []

  for (const s of filtered) {
    const name = s.name.toLowerCase()
    if (name.startsWith(q)) {
      prefix.push(s)
    } else if (name.includes(q)) {
      substring.push(s)
    }
    if (prefix.length + substring.length >= MAX_RESULTS * 2) break
  }

  return [...prefix, ...substring].slice(0, MAX_RESULTS)
}

// ─── Mapping to app model ─────────────────────────────────────────────────────

const SCHOOLS: SpellSchool[] = [
  'abjuration',
  'conjuration',
  'divination',
  'enchantment',
  'evocation',
  'illusion',
  'necromancy',
  'transmutation',
]

export function srdSchoolToApp(s: string): SpellSchool {
  const k = s.trim().toLowerCase() as SpellSchool
  return SCHOOLS.includes(k) ? k : 'abjuration'
}

/**
 * Composes the description the app uses with metadata that has no dedicated field
 * (components, duration, concentration, ritual, higher-level text).
 */
export function srdSpellToAppFields(s: SrdSpell): Omit<Spell, 'id' | 'prepared'> {
  const meta: string[] = []
  if (s.components) {
    meta.push(
      `Componentes: ${s.components}${s.material ? ` (${s.material})` : ''}`,
    )
  }
  if (s.duration) {
    meta.push(`Duração: ${s.duration}${s.concentration ? ' (Concentração)' : ''}`)
  }
  if (s.ritual) meta.push('Ritual')

  const parts = [s.description.trim()]
  if (s.higherLevel) parts.push(`Em níveis superiores: ${s.higherLevel.trim()}`)
  if (meta.length) parts.push(meta.join(' · '))

  return {
    name: s.name,
    level: s.level,
    school: srdSchoolToApp(s.school),
    castingTime: s.castingTime,
    range: s.range,
    description: parts.filter(Boolean).join('\n\n'),
  }
}
